# .streamlit/secrets.toml

[local.mysql]
dialect = "mysql"
host = "localhost"
port = 3306
database = "automotive"
username = "root"
password = "MySQL2022"

[mysql]
dialect = "mysql"
host = "sql12.freesqldatabase.com"
port = 3306
database = "sql12628633"
username = "sql12628633"
password = "tMKRnsnAFB"
